### ISSUE TITLE
Remove dependency on unicode_utils ?

### ISSUE THREAD

**Issue by fschwahn** [bmuller/gender_detector#16]
Hi,
I'm currently optimizing the boot time of my rails app, and realized that `unicode_utils` takes a lot of time to load (half a second on my development machine - on windows it seems worse: https://github.com/lang/unicode_utils/issues/6). What would you think about removing this dependency, and instead using it only if it is defined? Futhermore, ActiveSupport could be used if already present. A note to the README could be added that using UnicodeUtils is preferred, but the other ways are possible as well.

```ruby
def downcase(name)
  if defined?(UnicodeUtils)
    UnicodeUtils.downcase(name)
  elsif defined?(ActiveSupport::Multibyte::Chars)
    name.mb_chars.downcase.to_s
  else
    name.downcase
  end
end
```

I'd be willing to put together a PR if you think this is worthwhile.

All the best,
Fabian

**Comment by fschwahn** [comment]
@bmuller any chance you would merge this change if I put together a pull request? I'm running of a git version, but I generally prefer using released gem versions.

**Comment by bmuller** [comment]
Sure!  Thanks - and sorry for the lack of response!

**Comment by bmuller** [comment]
Done in #17
